name: flutterfix
description: A zero-config CLI tool that automatically fixes Flutter & Android build errors â€” resolving Gradle, Kotlin, Java, and Flutter version mismatches with one command.
version: 1.2.0
homepage: https://github.com/haraprosad/flutterfix
repository: https://github.com/haraprosad/flutterfix
issue_tracker: https://github.com/haraprosad/flutterfix/issues

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2
  http: ^1.2.0
  process_run: ^0.14.0
  cli_util: ^0.4.1
  mason_logger: ^0.2.0
  collection: ^1.18.0
  io: ^1.0.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
  mockito: ^5.4.0
  coverage: ^1.15.0

executables:
  flutterfix:
